# Generated by Django 5.1.4 on 2025-04-24 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam_sections", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("question_text", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("question_image", models.BinaryField(blank=True, null=True)),
                ("description_image", models.BinaryField(blank=True, null=True)),
                ("option_1", models.TextField()),
                ("option_2", models.TextField()),
                ("option_3", models.TextField(blank=True, null=True)),
                ("option_4", models.TextField(blank=True, null=True)),
                ("option_5", models.TextField(blank=True, null=True)),
                (
                    "correct_option",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="users.user",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam_sections.section",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "unique_together": {("section", "position")},
            },
        ),
    ]
