# Generated by Django 5.1.4 on 2025-04-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontype",
            name="exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_types",
                to="exams.exam",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questiontype",
            name="position",
            field=models.PositiveIntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questiontype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="questiontype",
            unique_together={("exam", "position")},
        ),
    ]
