# Generated by Django 5.1.4 on 2025-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="image_path",
        ),
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="description_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="description_images/"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
