# Generated by Django 5.1.4 on 2025-04-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="question",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
