# Generated by Django 5.1.4 on 2025-04-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_remove_question_image_path_question_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
