# Generated by Django 5.1.4 on 2025-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chosen_option_number",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("is_correct", models.BooleanField(null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_answers",
            },
        ),
    ]
