# Generated by Django 5.1.4 on 2025-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("has_fixed_structure", models.BooleanField(default=False)),
                ("default_question_count", models.IntegerField()),
                ("time_to_complete", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "exams",
            },
        ),
    ]
