# Generated by Django 5.1.4 on 2025-04-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="subjects",
            field=models.ManyToManyField(related_name="exams", to="subjects.subject"),
        ),
    ]
