# Generated by Django 5.1.4 on 2025-04-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                ("exam_code", models.CharField(max_length=50)),
                ("has_fixed_structure", models.BooleanField(default=False)),
                ("default_question_count", models.IntegerField()),
                ("time_to_complete", models.IntegerField()),
            ],
            options={
                "db_table": "sections",
            },
        ),
    ]
